name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URL with Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://juanberrio0399.github.io/
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: ./.lighthouserc.json
          minScore:
            performance: 90
            accessibility: 90
            best-practices: 90
            seo: 90
